// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC27JBuUExatcNCcaY8J3BjLnQWOpYeh6I',
    appId: '1:310676478091:web:3b7a41a14b9a0befe6dc8e',
    messagingSenderId: '310676478091',
    projectId: 'mygighirechat',
    authDomain: 'mygighirechat.firebaseapp.com',
    storageBucket: 'mygighirechat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-X-DvXi1eUdiAzd_SlPZgA69LsvZySQs',
    appId: '1:310676478091:android:8b807668c51c0dd2e6dc8e',
    messagingSenderId: '310676478091',
    projectId: 'mygighirechat',
    storageBucket: 'mygighirechat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkNM-hAjhAWt7GUZeXqKaU1uBS-TXKrXQ',
    appId: '1:310676478091:ios:35fcb58a7f2956d7e6dc8e',
    messagingSenderId: '310676478091',
    projectId: 'mygighirechat',
    storageBucket: 'mygighirechat.firebasestorage.app',
    iosBundleId: 'com.example.gighire',
  );
}
